### ISSUE TITLE
Tool looking for a config.json that doesn't exist

### ISSUE THREAD

**Issue by danfowler** [openspending/os-cli#28]
When trying to use this tool, it keeps looking for a `config.json` file that doesn't exist.  Setting `add_default` to `False` on [this line](https://github.com/openspending/os-cli/blob/master/oscli/services/config.py#L53) or manually adding an appropriate `config.json` allows me to use the tool.

```
(os-cli)legend:os-cli dan$ openspending config locate
null
(os-cli)legend:os-cli dan$ openspending config ensure
/Users/dan/.openspendingrc
(os-cli)legend:os-cli dan$ openspending config read
Traceback (most recent call last):
  File "/Users/dan/workspace_large/envs/os-cli/bin/openspending", line 9, in <module>
    load_entry_point('OSCLI==0.1.0a0', 'console_scripts', 'openspending')()
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/OSCLI-0.1.0a0-py2.7.egg/oscli/cli.py", line 49, in config
    config = services.config.read()
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/OSCLI-0.1.0a0-py2.7.egg/oscli/services/config.py", line 65, in read
    with io.open(DEFAULTPATH, encoding='utf-8') as file:
IOError: [Errno 2] No such file or directory: '/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/OSCLI-0.1.0a0-py2.7.egg/oscli/services/../config.json'
```

**Comment by roll** [comment]
@danfowler 
Could you reproduce it using `python -m oscli.cli config *` approach?

**Comment by danfowler** [comment]
Same:

```
(os-cli)legend:2013_suginami_budget_test dan$ python -m oscli.cli config locate
null
(os-cli)legend:2013_suginami_budget_test dan$ python -m oscli.cli config ensure
/Users/dan/.openspendingrc
(os-cli)legend:2013_suginami_budget_test dan$ python -m oscli.cli config read
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/OSCLI-0.1.0a0-py2.7.egg/oscli/cli.py", line 195, in <module>
    cli()
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/OSCLI-0.1.0a0-py2.7.egg/oscli/cli.py", line 49, in config
    config = services.config.read()
  File "/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/OSCLI-0.1.0a0-py2.7.egg/oscli/services/config.py", line 65, in read
    with io.open(DEFAULTPATH, encoding='utf-8') as file:
IOError: [Errno 2] No such file or directory: '/Users/dan/workspace_large/envs/os-cli/lib/python2.7/site-packages/OSCLI-0.1.0a0-py2.7.egg/oscli/services/../config.json'
```

**Comment by roll** [comment]
FIXED
